project:
  type: website
  execute-dir: project
  output-dir: docs

website:
  title: "Lyon Presentations"
  repo-url: https://github.com/njlyon0/lyon_talks
  repo-actions: [issue]
  navbar:
    left:
      - text: "LTER"
        href: home_lter.qmd
      - text: "Tutorials"
        href: home_tutorials.qmd
    right:
      - text: "Profile"
        href: https://njlyon0.github.io/
      - icon: github
        href: https://github.com/njlyon0/lyon_talks
        aria-label: GitHub
  page-footer:
    center: "Copyright 2024, Nicholas J Lyon"

execute:
  freeze: auto

format:
  html:
    code-overflow: wrap
    code-line-numbers: false
    code-copy: hover
    theme:
      light: lyonlight.scss
      dark: lyondark.scss
    mainfont: Open Sans
    toc: true
    link-external-newwindow: true
    link-external-icon: false
